allowBuilds:
  "@parcel/watcher": true
  "@swc/core": true
  esbuild: true
  sharp: true
minimumReleaseAgeExclude:
  - "@better-auth/core@1.6.13"
  - "@better-auth/drizzle-adapter@1.6.13"
  - "@better-auth/kysely-adapter@1.6.13"
  - "@better-auth/memory-adapter@1.6.13"
  - "@better-auth/mongo-adapter@1.6.13"
  - "@better-auth/prisma-adapter@1.6.13"
  - "@better-auth/telemetry@1.6.13"
  - better-auth@1.6.13
  - lint-staged@17.0.7
  - react-hook-form@7.77.0
  - tinyexec@1.2.4
  - tsx@4.22.4
