services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-container
    ports:
      - '27017:27017'
    volumes:
      - ./mongodb:/data/db
      - ./mongo-init/:/docker-entrypoint-initdb.d/:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
